SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO AS FI
WHERE FI.FISH_TYPE IN (SELECT FN.FISH_TYPE
                      FROM FISH_NAME_INFO AS FN
                      WHERE FISH_NAME IN ('BASS', 'SNAPPER'));